[package]
name = "dtools"
version = "0.1.0"
authors = ["DCjanus <DCjanus@dcjanus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.6.2"
anyhow = "1.0.35"
clap = "3.0.0-beta.2"
